<?php

use Illuminate\Database\Seeder;

class MediablesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('mediables')->delete();
        
        \DB::table('mediables')->insert(array (
            0 => 
            array (
                'id' => 68,
                'created_at' => '2018-10-31 16:53:41',
                'updated_at' => '2018-10-31 16:53:41',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 280,
                'crop_w' => 677,
                'crop_h' => 382,
                'role' => 'cover',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'landscape',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
            ),
            1 => 
            array (
                'id' => 69,
                'created_at' => '2018-10-31 16:53:41',
                'updated_at' => '2018-10-31 16:53:41',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 62,
                'crop_y' => 0,
                'crop_w' => 661,
                'crop_h' => 662,
                'role' => 'cover',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
            ),
            2 => 
            array (
                'id' => 70,
                'created_at' => '2018-10-31 16:53:41',
                'updated_at' => '2018-10-31 16:53:41',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 5,
                'crop_x' => 0,
                'crop_y' => 113,
                'crop_w' => 1600,
                'crop_h' => 900,
                'role' => 'top',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'landscape',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
            ),
            3 => 
            array (
                'id' => 78,
                'created_at' => '2018-11-02 19:41:53',
                'updated_at' => '2018-11-02 19:41:53',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 2,
                'crop_x' => 202,
                'crop_y' => 247,
                'crop_w' => 185,
                'crop_h' => 104,
                'role' => 'top',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'landscape',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
            ),
            4 => 
            array (
                'id' => 79,
                'created_at' => '2018-11-02 19:41:53',
                'updated_at' => '2018-11-02 19:41:53',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 5,
                'crop_x' => 0,
                'crop_y' => 113,
                'crop_w' => 1600,
                'crop_h' => 900,
                'role' => 'top',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'landscape',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
            ),
            5 => 
            array (
                'id' => 80,
                'created_at' => '2018-11-02 19:41:53',
                'updated_at' => '2018-11-02 19:41:53',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 207,
                'crop_w' => 811,
                'crop_h' => 455,
                'role' => 'cover',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'landscape',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
            ),
            6 => 
            array (
                'id' => 81,
                'created_at' => '2018-11-02 19:41:53',
                'updated_at' => '2018-11-02 19:41:53',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 3,
                'crop_x' => 62,
                'crop_y' => 0,
                'crop_w' => 662,
                'crop_h' => 662,
                'role' => 'cover',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
            ),
            7 => 
            array (
                'id' => 82,
                'created_at' => '2018-11-02 19:41:53',
                'updated_at' => '2018-11-02 19:41:53',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 4,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 1370,
                'crop_h' => 771,
                'role' => 'cover',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'landscape',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
            ),
            8 => 
            array (
                'id' => 83,
                'created_at' => '2018-11-02 19:41:53',
                'updated_at' => '2018-11-02 19:41:53',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 4,
                'crop_x' => 24,
                'crop_y' => 0,
                'crop_w' => 771,
                'crop_h' => 771,
                'role' => 'cover',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
            ),
            9 => 
            array (
                'id' => 84,
                'created_at' => '2018-11-02 19:41:53',
                'updated_at' => '2018-11-02 19:41:53',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 2,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 474,
                'crop_h' => 267,
                'role' => 'testImages',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'landscape',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
            ),
            10 => 
            array (
                'id' => 85,
                'created_at' => '2018-11-02 19:41:53',
                'updated_at' => '2018-11-02 19:41:53',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Project',
                'media_id' => 2,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 474,
                'crop_h' => 474,
                'role' => 'testImages',
                'crop' => 'mobile',
                'lqip_data' => NULL,
                'ratio' => 'mobile',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
            ),
            11 => 
            array (
                'id' => 98,
                'created_at' => '2018-11-02 20:11:50',
                'updated_at' => '2018-11-02 20:11:50',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\Newsitem',
                'media_id' => 2,
                'crop_x' => 0,
                'crop_y' => 160,
                'crop_w' => 474,
                'crop_h' => 267,
                'role' => 'img_standard',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'landscape',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
            ),
            12 => 
            array (
                'id' => 99,
                'created_at' => '2018-11-02 20:11:50',
                'updated_at' => '2018-11-02 20:11:50',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\Newsitem',
                'media_id' => 3,
                'crop_x' => 91,
                'crop_y' => 79,
                'crop_w' => 517,
                'crop_h' => 517,
                'role' => 'img_mobile',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'landscape',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
            ),
            13 => 
            array (
                'id' => 100,
                'created_at' => '2018-11-06 15:47:00',
                'updated_at' => '2018-11-06 15:47:00',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\Infopage',
                'media_id' => 2,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 474,
                'crop_h' => 317,
                'role' => 'main_image',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => '3:2',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
            ),
            14 => 
            array (
                'id' => 101,
                'created_at' => '2018-11-06 15:47:00',
                'updated_at' => '2018-11-06 15:47:00',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\Infopage',
                'media_id' => 3,
                'crop_x' => 0,
                'crop_y' => 103,
                'crop_w' => 811,
                'crop_h' => 540,
                'role' => 'sm_image',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => '3:2',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
            ),
            15 => 
            array (
                'id' => 112,
                'created_at' => '2018-11-06 17:24:56',
                'updated_at' => '2018-11-06 17:24:56',
                'deleted_at' => NULL,
                'mediable_id' => 5,
                'mediable_type' => 'App\\Models\\Staffmember',
                'media_id' => 6,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 689,
                'crop_h' => 688,
                'role' => 'image',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'square',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
            ),
            16 => 
            array (
                'id' => 113,
                'created_at' => '2018-11-06 17:25:52',
                'updated_at' => '2018-11-06 17:25:52',
                'deleted_at' => NULL,
                'mediable_id' => 4,
                'mediable_type' => 'App\\Models\\Staffmember',
                'media_id' => 7,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 689,
                'crop_h' => 688,
                'role' => 'image',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'square',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
            ),
            17 => 
            array (
                'id' => 114,
                'created_at' => '2018-11-06 17:26:00',
                'updated_at' => '2018-11-06 17:26:00',
                'deleted_at' => NULL,
                'mediable_id' => 3,
                'mediable_type' => 'App\\Models\\Staffmember',
                'media_id' => 9,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 689,
                'crop_h' => 688,
                'role' => 'image',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'square',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
            ),
            18 => 
            array (
                'id' => 115,
                'created_at' => '2018-11-06 17:26:04',
                'updated_at' => '2018-11-06 17:26:04',
                'deleted_at' => NULL,
                'mediable_id' => 2,
                'mediable_type' => 'App\\Models\\Staffmember',
                'media_id' => 8,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 689,
                'crop_h' => 688,
                'role' => 'image',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'square',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
            ),
            19 => 
            array (
                'id' => 116,
                'created_at' => '2018-11-06 17:26:09',
                'updated_at' => '2018-11-06 17:26:09',
                'deleted_at' => NULL,
                'mediable_id' => 1,
                'mediable_type' => 'App\\Models\\Staffmember',
                'media_id' => 10,
                'crop_x' => 0,
                'crop_y' => 0,
                'crop_w' => 689,
                'crop_h' => 688,
                'role' => 'image',
                'crop' => 'default',
                'lqip_data' => NULL,
                'ratio' => 'square',
                'metadatas' => '{"video": null, "altText": null, "caption": null}',
            ),
        ));
        
        
    }
}